---
title: "Untitled"
author: "Nick Gauthier"
date: "9/1/2020"
output: html_document
---

```{r}
bbox <- extent(c(-125, -102, 31, 49))
```

```{r}
ppt <- list.files('~/Downloads/PRISM/PRISM_ppt_stable_4kmM3_198101_201904_bil', full.names = TRUE, pattern = '.bil$') %>%
  map(~raster(.) %>% crop(bbox)) %>%
  brick %>%
  aggregate(fact = 2) %>%
  crop(states_wus)

ppt2 <- names(ppt) %>% str_split('_') %>% map_chr(~.[[5]]) %>% setNames(ppt, .)

tmean <- list.files('~/Downloads/PRISM/PRISM_tmean_stable_4kmM3_198101_201904_bil', full.names = TRUE, pattern = '.bil$') %>%
  map(~raster(.) %>% crop(bbox)) %>%
  brick %>%
  aggregate(fact = 2) %>%
  crop(states_wus)

tmean2 <- names(tmean) %>% str_split('_') %>% map_chr(~.[[5]]) %>% setNames(tmean, .)
```

```{r}
ppt_dat <- ppt2 %>%
  as.data.frame(xy = TRUE, na.rm = TRUE, long = TRUE) %>%
  mutate(time = parse_number(layer)) %>%
  separate(time, into = c('year', 'month'), sep = -2, convert = TRUE) %>%
  select(-layer) %>%
  filter(month %in% c(1,2,3)) %>%
  group_by(x, y, year) %>%
  summarise(value = sum(value, na.rm = TRUE)) %>% # diff from temp
  ungroup()

tmean_dat <- tmean2 %>%
  as.data.frame(xy = TRUE, na.rm = TRUE, long = TRUE) %>%
  mutate(time = parse_number(layer)) %>%
  separate(time, into = c('year', 'month'), sep = -2, convert = TRUE) %>%
  select(-layer) %>%
  filter(month %in% c(1,2,3)) %>%
  group_by(x, y, year) %>%
  summarise(value = mean(value, na.rm = TRUE)) %>% # diff from precip
  ungroup()
```


```{r}
pc_amps <- prism_patterns$amplitudes %>%
  spread(PC, amplitude, sep ='')

ppt_corr <- ppt_dat %>%
  group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor(value, PC1),
              PC2 = cor(value, PC2),
              PC3 = cor(value, PC3),
              PC4 = cor(value, PC4)))) %>%
  select(-data) %>%
  unnest(corrs)


tmean_corr <-tmean_dat %>%
  group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor(value, PC1),
              PC2 = cor(value, PC2),
              PC3 = cor(value, PC3),
              PC4 = cor(value, PC4)))) %>%
  select(-data) %>%
  unnest(corrs)
```


```{r, warning = FALSE}
world <- maps::map('world',wrap=c(0,360),fill = TRUE, plot = FALSE)

sst_mean <- mean(brick('~/gdrive/Projects/snow-wna/data/sst.mon.ltm.1981-2010.nc', varname = 'sst')[[1:3]])

sst_brick <- brick('~/gdrive/Projects/snow-wna/data/sst.mnmean.nc', varname = 'sst')

time <- getZ(sst_brick)
id <- which(time >= as.Date('1982-01-01') & time <= as.Date('2017-03-01') & str_detect(time, c('-01-', '-02-', '-03-')))

sst_jfm <- subset(sst_brick, id) %>%
  stackApply(rep(1:36, each = 3), 'mean') %>% 
  `-`(sst_mean) %>% 
  crop(extent(c(-1, 359, -75, 75))) %>%
  disaggregate(fact = 2, method = 'bilinear')
```

```{r}
geop_jfm <- brick('../data/adaptor.mars.internal-1584737536.594777-6445-11-8d0fcc69-bd7d-40e2-a423-cf86c741ac79.nc')[[-(1:3)]] %>%
   stackApply(rep(1:36, each = 3), 'mean') %>%
    `-`(., mean(.)) %>%
  aggregate(fact = 4, method = 'bilinear')

geop_corr <- geop_jfm%>% setNames(1982:2017) %>%
  as.data.frame(xy = TRUE, na.rm = TRUE, long = TRUE) %>%
  mutate(year = parse_number(layer)) %>%
  select(-layer) %>%
   group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor(value, PC1),
              PC2 = cor(value, PC2),
              PC3 = cor(value, PC3),
              PC4 = cor(value, PC4)))) %>%
  select(-data) %>%
  unnest(corrs)
```


```{r}
sst_corr <- sst_jfm %>% setNames(1982:2017) %>%
  as.data.frame(xy = TRUE, na.rm = TRUE, long = TRUE) %>%
  mutate(year = parse_number(layer)) %>%
  select(-layer) %>%
   group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor(value, PC1),
              PC2 = cor(value, PC2),
              PC3 = cor(value, PC3),
              PC4 = cor(value, PC4)))) %>%
  select(-data) %>%
  unnest(corrs)
```


```{r}
sst_sig_pts <- sst_jfm %>% setNames(1982:2017) %>%
  as.data.frame(xy = TRUE, na.rm = TRUE, long = TRUE) %>%
  mutate(year = parse_number(layer)) %>%
  select(-layer) %>%
   group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor.test(value, PC1)$p.value,
              PC2 = cor.test(value, PC2)$p.value,
              PC3 = cor.test(value, PC3)$p.value,
              PC4 = cor.test(value, PC4)$p.value))) %>%
  select(-data) %>%
  unnest(corrs) %>%
    gather(PC, value, PC1:PC4) %>%
    group_by(PC) %>%
    mutate(value = p.adjust(value, method = 'fdr')) %>%
  filter(value < 0.1) %>%
  ungroup

geop_sig_pts <- geop_jfm %>% setNames(1982:2017) %>%
  as.data.frame(xy = TRUE, na.rm = TRUE, long = TRUE) %>%
  mutate(year = parse_number(layer)) %>%
  select(-layer) %>%
   group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor.test(value, PC1)$p.value,
              PC2 = cor.test(value, PC2)$p.value,
              PC3 = cor.test(value, PC3)$p.value,
              PC4 = cor.test(value, PC4)$p.value))) %>%
  select(-data) %>%
  unnest(corrs) %>%
    gather(PC, value, PC1:PC4) %>%
    group_by(PC) %>%
    mutate(value = p.adjust(value, method = 'fdr')) %>%
  filter(value < 0.1) %>%
  ungroup

ppt_sig_pts <- ppt_dat %>%
   group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor.test(value, PC1)$p.value,
              PC2 = cor.test(value, PC2)$p.value,
              PC3 = cor.test(value, PC3)$p.value,
              PC4 = cor.test(value, PC4)$p.value))) %>%
  select(-data) %>%
  unnest(corrs) %>%
    gather(PC, value, PC1:PC4) %>%
    group_by(PC) %>%
    mutate(value = p.adjust(value, method = 'fdr')) %>%
  filter(value < 0.1) %>%
  ungroup

tmean_sig_pts <- tmean_dat %>%
   group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor.test(value, PC1)$p.value,
              PC2 = cor.test(value, PC2)$p.value,
              PC3 = cor.test(value, PC3)$p.value,
              PC4 = cor.test(value, PC4)$p.value))) %>%
  select(-data) %>%
  unnest(corrs) %>%
    gather(PC, value, PC1:PC4) %>%
    group_by(PC) %>%
    mutate(value = p.adjust(value, method = 'fdr')) %>%
  filter(value < 0.1) %>%
  ungroup

swe_sig_pts <- prism_dat %>%
   group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., pc_amps, by = 'year') %>%
    summarise(PC1 = cor.test(SWE, PC1)$p.value,
              PC2 = cor.test(SWE, PC2)$p.value,
              PC3 = cor.test(SWE, PC3)$p.value,
              PC4 = cor.test(SWE, PC4)$p.value))) %>%
  select(-data) %>%
  unnest(corrs) %>%
    gather(PC, value, PC1:PC4) %>%
    group_by(PC) %>%
    mutate(value = p.adjust(value, method = 'fdr')) %>%
  filter(value < 0.1) %>%
  ungroup
```



## Interpretation

```{r, echo = FALSE}
a <- prism_patterns%>%
    dplyr::select(-amplitudes) %>%
    unnest(patterns) %>%
    mutate(EOF = paste0('EOF', PC)) %>%
  left_join(prism_climatology) %>%
  ggplot() +
      geom_raster(aes(x, y, fill = weight/swe_sd)) +
      geom_sf(data = states_wus, fill = NA, color = 'black') +
      facet_wrap(~EOF, ncol = 1) +
      scale_fill_scico(name = 'weight/sdev', palette = 'vik', direction = 1, limits = c(-1, 1) ) +
      theme_void()+
  theme(legend.position = 'bottom')


b<- sst_cor %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  gather(eof, value, starts_with('PC')) %>%
  #  filter(value > .1 | value < -.1) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
  geom_point(data = sst_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~eof, ncol = 1) +
  scale_fill_distiller(name = 'Corr.', palette = 'RdBu', limits = c(-1,1)) +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
  labs(x = 'Longitude', y = 'Latitude') +
  theme_bw() +
  theme(legend.position = 'bottom')


c<-geop_cor %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  gather(eof, value, starts_with('PC')) %>%
  #  filter(value > .1 | value < -.1) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
    geom_polygon(data = world, aes(x = long, y = lat, group = group), alpha = .25) +
  geom_point(data = geop_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~eof, ncol = 1) +
  scale_fill_distiller(name = 'Corr.', palette = 'RdBu', limits = c(-1,1)) +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  labs(x = 'Longitude', y = 'Latitude') +
  theme_bw()+
  theme(legend.position = 'bottom')

#library(patchwork)  
(a|b|c) + plot_layout(widths = c(1, 1,1)) + plot_annotation(tag_levels = 'A')
ggsave('snow_teleconnections.png', height =8.5, width = 11)
#ggsave('snow_telecon_cov.png')
```


```{r}

# sst_corr %>%
#   gather(PC, value, PC1:PC4) %>%
# ggplot(aes(x, y)) +
#   geom_raster(aes(fill = value)) +
#     geom_point(data = test.pts, shape = '.', alpha = .075) +
#   facet_wrap(~PC, nrow = 3) +
#   coord_quickmap(ylim = c(-75,75), expand = FALSE) +
#     geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
#   scale_fill_distiller(name = 'Correlation', palette = 'RdBu', limits = c(-1,1)) +
#     labs(x = 'Longitude', y = 'Latitude') +
#   theme_bw()

a <- ppt_corr %>%
  gather(PC, value, PC1:PC4) %>%
ggplot() +
  geom_raster(aes(x, y, fill = value)) +
        geom_sf(data = states_wus, fill = NA, color = 'black') +
    geom_point(data = ppt_sig_pts, aes(x, y), shape = '.', alpha = .075) +
  facet_wrap(~PC, ncol = 1) +
scale_fill_scico(palette = 'vikO', limits = c(-1, 1), name = 'Correlation') +
    labs(x = 'Longitude', y = 'Latitude') +
  theme_void()

b <- tmean_corr %>%
  gather(PC, value, PC1:PC4) %>%
ggplot() +
  geom_raster(aes(x, y, fill = value)) +
        geom_sf(data = states_wus, fill = NA, color = 'black') +
    geom_point(data = tmean_sig_pts, aes(x,y), shape = '.', alpha = .075) +
  facet_wrap(~PC, ncol = 1) +
scale_fill_scico(palette = 'vikO', limits = c(-1, 1), name = 'Correlation') +
    labs(x = 'Longitude', y = 'Latitude') +
  theme_void()

c <- geop_corr %>%
    gather(PC, value, PC1:PC4) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
    geom_polygon(data = world, aes(x = long, y = lat, group = group), alpha = .35) +
  geom_point(data = geop_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~PC, ncol = 1) +
scale_fill_scico(palette = 'vikO', limits = c(-1, 1), name = 'Correlation') +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  labs(x = 'Longitude', y = 'Latitude') +
   theme_void() +
  theme(panel.border = element_rect(fill = NA, 
            colour = "grey20"), panel.spacing = unit(1, "lines"))

d <- sst_corr %>% 
      gather(PC, value, PC1:PC4) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
  geom_point(data = sst_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~PC, ncol = 1) +
scale_fill_scico(palette = 'vikO', limits = c(-1, 1), name = 'Correlation') +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
  theme_void() +
  theme(panel.border = element_rect(fill = NA, 
            colour = "grey20"), panel.spacing = unit(1, "lines"))
  
  

#   # swe_corr %>%
# #   gather(PC, value, PC1:PC4) %>%
# ggplot(aes(x, y)) +
#   geom_raster(aes(fill = value)) +
#     geom_point(data = swe_sig_pts, shape = '.', alpha = .075) +
#   facet_wrap(~PC) +
#   coord_quickmap() +
#   scale_fill_scico(palette = 'vik', direction = -1, limits = c(-1, 1)) 
```

```{r}
library(patchwork)
```


```{r fig.width = 10.5, fig.height = 6}
(a | b | c | d) + plot_layout(guides = 'collect', widths = c(1,1,1.3, 1.3)) + plot_annotation(tag_levels = 'A') & theme(legend.position = 'bottom')
```



```{r}
ggsave('snow_teleconnections.png', width = 10.5, height = 6)
```

```{r, fig.width = 7, fig.height = 6}
swe_corr_prism <-prism_dat %>%
  group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., prism_patterns$amplitudes %>% spread(PC, amplitude, sep =''), by = 'year') %>%
    summarise(PC1 = cor(SWE, PC1),
              PC2 = cor(SWE, PC2),
              PC3 = cor(SWE, PC3),
              PC4 = cor(SWE, PC4)))) %>%
  select(-data) %>%
  unnest(corrs)

swe_corr_cera <-cera_dat %>%
  group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., cera_patterns$amplitudes %>% spread(PC, amplitude, sep =''), by = 'year') %>%
    summarise(PC1 = cor(SWE, PC1),
              PC2 = cor(SWE, PC2),
              PC3 = cor(SWE, PC3),
              PC4 = cor(SWE, PC4)))) %>%
  select(-data) %>%
  unnest(corrs)

cesm_patterns <- get_patterns(cesm_dat %>% select(-area) %>% filter(year > 1900,x < max(x), y > min(y)), k = n_modes)
swe_corr_cesm <- cesm_dat %>%
  filter(year > 1900,x < max(x), y > min(y)) %>%
  group_by(x,y) %>%
  nest %>%
  mutate(corrs = map(data,  ~inner_join(., cesm_patterns$amplitudes %>% spread(PC, amplitude, sep =''), by = 'year') %>%
    summarise(PC1 = cor(SWE, PC1),
              PC2 = cor(SWE, PC2),
              PC3 = cor(SWE, PC3),
              PC4 = cor(SWE, PC4)))) %>%
  select(-data) %>%
  unnest(corrs)

a <- swe_corr_prism %>%
  gather(PC, value, PC1:PC4) %>%
ggplot() +
  geom_raster(aes(x, y, fill = value)) +
        geom_sf(data = states_wus, fill = NA, color = 'black') +
 #   geom_point(data = swe_sig_pts, aes(x,y), shape = '.', alpha = .2) +
  facet_wrap(~PC, nrow = 1) +
scale_fill_scico(palette = 'broc', limits = c(-1, 1), name = 'Correlation') +
    labs(x = 'Longitude', y = 'Latitude') +
  theme_void()

b <- swe_corr_cera %>%
  mutate(PC1 = PC1 * -1, PC2 = PC2 * -1, PC3 = PC3 * -1) %>% # the signs are arbitrary, so adjust the cera signs so the colors match prism
  gather(PC, value, PC1:PC4) %>%
ggplot() +
  geom_raster(aes(x, y, fill = value)) +
        geom_sf(data = states_wus, fill = NA, color = 'black') +
 #   geom_point(data = swe_sig_pts, aes(x,y), shape = '.', alpha = .2) +
  facet_wrap(~PC, nrow = 1) +
scale_fill_scico(palette = 'broc', limits = c(-1, 1), name = 'Correlation') +
    labs(x = 'Longitude', y = 'Latitude') +
  theme_void()

c <- swe_corr_cesm %>%
  remove_missing() %>%
  mutate(PC3 = PC3 * -1) %>% # the signs are arbitrary, so adjust the cera signs so the colors match prism
  gather(PC, value, PC1:PC4) %>%
ggplot() +
  geom_raster(aes(x, y, fill = value)) +
        geom_sf(data = states_wus, fill = NA, color = 'black') +
 #   geom_point(data = swe_sig_pts, aes(x,y), shape = '.', alpha = .2) +
  facet_wrap(~PC, nrow = 1) +
scale_fill_scico(palette = 'broc', limits = c(-1, 1), name = 'Correlation') +
    labs(x = 'Longitude', y = 'Latitude') +
  theme_void()

(a / b / c) + plot_layout(guides = 'collect') + plot_annotation(tag_levels = 'A') & theme(legend.position = 'bottom')
ggsave('eofs_cesm.png', height = 6, width = 7)
```

```{r}
cera_patterns$amplitudes %>% filter(PC == '2') %>%
  left_join(cesm_patterns$amplitudes %>% filter(PC == '2'), by = c('year')) %>% summarise(cor(amplitude.x, amplitude.y, use = 'complete.obs'))
```


```{r,  echo = FALSE}
sst_cor %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  gather(eof, value, starts_with('PC')) %>%
  #  filter(value > .1 | value < -.1) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
  geom_point(data = sst_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~eof, nrow = 3) +
  scale_fill_distiller(name = 'Correlation', palette = 'RdBu', limits = c(-1,1)) +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
  labs(title = 'Snow teleconnections', 
       subtitle = 'PC correlation to JFM sea surface temperature',
       x = 'Longitude', y = 'Latitude') +
  theme_bw()
  
#ggsave('sst_telecon_cov.png')
```

```{r,  echo = FALSE}
sst_cor %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  gather(eof, value, starts_with('PC')) %>%
  #  filter(value > .1 | value < -.1) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
  geom_point(data = sst_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~eof, nrow = 3) +
  scale_fill_distiller(name = 'Correlation', palette = 'RdBu', limits = c(-1,1)) +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) +
  labs(title = 'Snow teleconnections', 
       subtitle = 'PC correlation to JFM sea surface temperature',
       x = 'Longitude', y = 'Latitude') +
  theme_bw()
  
#ggsave('sst_telecon_cov.png')
```



```{r, echo = FALSE}
geop_cor %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  gather(eof, value, starts_with('PC')) %>%
  #  filter(value > .1 | value < -.1) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
    geom_polygon(data = world, aes(x = long, y = lat, group = group), alpha = .25) +
  geom_point(data = geop_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~eof, nrow = 3) +
  scale_fill_distiller(name = 'Correlation', palette = 'RdBu', limits = c(-1,1)) +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  labs(title = 'Snow teleconnections', 
       subtitle = 'PC correlation to JFM 500mb geopotential height',
       x = 'Longitude', y = 'Latitude') +
  theme_bw()
  
#ggsave('geop_telecon_cov.png')
```

```{r, echo = FALSE}
geop_cor %>% 
  as.data.frame(xy = T, na.rm = T) %>%
  gather(eof, value, starts_with('PC')) %>%
  #  filter(value > .1 | value < -.1) %>%
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = value)) +
    geom_polygon(data = world, aes(x = long, y = lat, group = group), alpha = .25) +
  geom_point(data = geop_sig_pts, shape = '.', alpha = .075) +
  facet_wrap(~eof, nrow = 3) +
  scale_fill_distiller(name = 'Correlation', palette = 'RdBu', limits = c(-1,1)) +
  coord_quickmap(ylim = c(-75,75), expand = FALSE) +
  labs(title = 'Snow teleconnections', 
       subtitle = 'PC correlation to JFM 500mb geopotential height',
       x = 'Longitude', y = 'Latitude') +
  theme_bw()
  
#ggsave('geop_telecon_cov.png')
```

