---
title: "Untitled"
author: "Nick Gauthier"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
get_patterns(temp_anomalies, k = 3)|> plot()
```

```{r}
get_patterns(temp_anomalies, k = 3, scale = TRUE )|> plot()

```
```{r}
get_patterns(temp_anomalies, k = 5, scale = TRUE, rotate = TRUE )|> plot()
get_patterns(temp_anomalies, k = 5, scale = FALSE, rotate = FALSE )|> plot()
get_patterns(temp_anomalies, k = 5, scale = TRUE, rotate = FALSE )|> plot()
get_patterns(temp_anomalies, k = 5, scale = FALSE, rotate = TRUE )|> plot()
```

```{r}
hex <- st_make_grid(temp_anomalies, square = FALSE)
temp_hex <- aggregate(temp_anomalies, hex, mean)

get_patterns(temp_hex, k = 5) |> plot()

st_area(temp_anomalies) |> plot()

st_area(temp_hex)
```

```{r}
screeplot(patterns)
```

```{r}
reconstruct_field(patterns, nonneg = FALSE) |> plot()
plot(temp_anomalies)

get_anomalies(temp_anomalies) |> plot()
get_climatology(temp_anomalies) |> plot()
patterns

str(patterns$units)
```

```{r}
patterns <- get_patterns(temp_anomalies, k=4, weight=FALSE)

  plot(anomalies[,,,1:4])
  plot(temp_anomalies[,,,1:4])
  plot(reconstruct_field(patterns, nonneg = FALSE)[,,,1:4])

        plot(temp_anomalies[,,,1:4])

get_anomalies(temp_anomalies)[,,,1:4] |> plot()


```

```{r}
reconstruct_field
```
```{r}
patterns<- get_patterns(temp_anomalies, k=4)
plot(patterns)

anomalies <- patterns$amplitudes %>%
    rowwise() %>%
    mutate(PCs = list(c_across(-time)), .keep = 'unused') %>%
    ungroup() %>%
    tibble::deframe() %>%
    purrr::map(~sweep(patterns$eofs, MARGIN = 3, STATS = .x, FUN = "*")) %>%
    do.call('c', .) %>%
    stars::st_apply(1:2, sum) %>%
    merge(name = 'time') %>%
    stars::st_set_dimensions('time', values = patterns$amplitudes$time) %>%
    setNames(patterns$names)
patterns_rot <- get_patterns(temp_anomalies, k=4, rotate = TRUE)
plot(patterns_rot)
anomalies_rot <- patterns_rot$amplitudes %>%
    rowwise() %>%
    mutate(PCs = list(c_across(-time)), .keep = 'unused') %>%
    ungroup() %>%
    tibble::deframe() %>%
    purrr::map(~sweep(patterns_rot$eofs, MARGIN = 3, STATS = .x, FUN = "*")) %>%
    do.call('c', .) %>%
    stars::st_apply(1:2, sum) %>%
    merge(name = 'time') %>%
    stars::st_set_dimensions('time', values = patterns_rot$amplitudes$time) %>%
    setNames(patterns_rot$names)

plot(anomalies[,,,1:4]);plot(anomalies_rot[,,,1:4]);plot(get_anomalies(temp_anomalies)[,,,1:4])

  final <- restore_climatology(anomalies,
                               clim = target_patterns$climatology,
                               scale = target_patterns$scaled,
                               monthly = target_patterns$monthly)

  if(target_patterns$weight) {
    # Handle units properly for division by area weights
    weights <- area_weights(final)
    final <- units::drop_units(final) / weights
    # Units will be restored later in the function
  }
  if(nonneg) final <- mutate(final, across(everything(), ~pmax(.x, 0 * .x)))

  # Restore units for each variable
  if(!is.null(target_patterns$units) && any(!sapply(target_patterns$units, is.null))) {
    for(var_name in names(target_patterns$units)) {
      if(!is.null(target_patterns$units[[var_name]])) {
        final[[var_name]] <- units::set_units(final[[var_name]], target_patterns$units[[var_name]], mode = 'standard')
      }
    }
  }


  plot(patterns$eofs)
```
```{r}
get_patterns(temp_anomalies, k = 3)|> reconstruct_field() %>% .[,,,1:4] |> plot()
get_patterns(temp_anomalies, k = 3, rotate = TRUE)|> reconstruct_field() %>% .[,,,1:4] |> plot()
plot(temp_anomalies[,,,1:4])
```

```{r}
predictor_patterns <- get_patterns(temp_anomalies, k = 6, rotate = TRUE, scale = TRUE)
response_patterns  <- get_patterns(temp_anomalies[,,,c(2:36, 1)],  k = 6, rotate = TRUE, scale = TRUE)

cca_fit <- couple_patterns(predictor_patterns, response_patterns)
response_recon <- predict(cca_fit, temp_anomalies, k = 6)
plot(response_recon)
plot(temp_anomalies)
get_canonical_variables(cca_fit, predictor_patterns)
get_canonical_correlations(cca_fit)

plot(cca_fit)

dim(cca_fit$cca$xcoef)
dim(cca_fit$cca$ycoef)

predict(cca_fit, temp_anomalies, k = 3) |> plot(
  
)
```

